/* This file was generated by the Hex-Rays decompiler version 8.2.0.221215.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
int sub_80484A0();
// int __cdecl __cxa_atexit(void (__cdecl *lpfunc)(void *), void *obj, void *lpdso_handle);
// int __gmon_start__(void); weak
// _DWORD std::ios_base::Init::Init(std::ios_base::Init *__hidden this); idb
// int __cdecl __libc_start_main(int (__cdecl *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// void _exit(int status);
// void __cdecl std::ios_base::Init::~Init(void *); idb
// void *memcpy(void *dest, const void *src, size_t n);
// size_t strlen(const char *s);
// _DWORD __cdecl operator new(unsigned int); idb
// void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>);
void _do_global_dtors_aux();
int frame_dummy();
int __cdecl main(int argc, const char **argv, const char **envp);
int __cdecl __static_initialization_and_destruction_0(int a1, int a2);
int GLOBAL__sub_I_main();
void __cdecl N::N(N *this, int a2);
void *__cdecl N::setAnnotation(N *this, char *s);
int __cdecl N::operator+(int a1, int a2);
int __cdecl N::operator-(int a1, int a2);
void _libc_csu_init(void); // idb
void _libc_csu_fini(void); // idb
void (*_do_global_ctors_aux())(void);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int (__cdecl *off_8048848[2])(int, int) = { &N::operator+, &N::operator- }; // weak
int (*_init_array_start)() = &GLOBAL__sub_I_main; // weak
int _CTOR_LIST__ = -1; // weak
int _DTOR_LIST__[] = { -1 }; // weak
int _DTOR_END__ = 0; // weak
int _JCR_LIST__ = 0; // weak
Elf32_Dyn *GLOBAL_OFFSET_TABLE_ = &DYNAMIC; // weak
int (*dword_8049B4C)(void) = NULL; // weak
_UNKNOWN _dso_handle; // weak
char completed_6159; // weak
int dtor_idx_6161; // weak
_UNKNOWN std::__ioinit; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (08048464) --------------------------------------------------------
void (*init_proc())(void)
{
  if ( &_gmon_start__ )
    __gmon_start__();
  frame_dummy();
  return _do_global_ctors_aux();
}
// 80484C0: using guessed type int __gmon_start__(void);

//----- (080484A0) --------------------------------------------------------
int sub_80484A0()
{
  return dword_8049B4C();
}
// 8049B4C: using guessed type int (*dword_8049B4C)(void);

//----- (08048540) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall __noreturn start(int a1@<eax>, void (*a2)(void)@<edx>)
{
  int v2; // esi
  int v3; // [esp-4h] [ebp-4h] BYREF
  char *retaddr; // [esp+0h] [ebp+0h] BYREF

  v2 = v3;
  v3 = a1;
  __libc_start_main((int (__cdecl *)(int, char **, char **))main, v2, &retaddr, _libc_csu_init, _libc_csu_fini, a2, &v3);
  __halt();
}
// 8048543: positive sp value 4 has been found

//----- (08048570) --------------------------------------------------------
void _do_global_dtors_aux()
{
  int v0; // eax
  unsigned int i; // ebx

  if ( !completed_6159 )
  {
    v0 = dtor_idx_6161;
    for ( i = &_DTOR_END__ - _DTOR_LIST__ - 1; dtor_idx_6161 < i; v0 = dtor_idx_6161 )
    {
      dtor_idx_6161 = v0 + 1;
      ((void (*)(void))_DTOR_LIST__[v0 + 1])();
    }
    completed_6159 = 1;
  }
}
// 8049A54: using guessed type int _DTOR_LIST__[];
// 8049A58: using guessed type int _DTOR_END__;
// 8049BAC: using guessed type char completed_6159;
// 8049BB0: using guessed type int dtor_idx_6161;

//----- (080485D0) --------------------------------------------------------
int frame_dummy()
{
  int result; // eax

  result = _JCR_LIST__;
  if ( _JCR_LIST__ )
    return 0;
  return result;
}
// 8049A5C: using guessed type int _JCR_LIST__;

//----- (0804870E) --------------------------------------------------------
void *__cdecl N::setAnnotation(N *this, char *s)
{
  size_t v2; // eax

  v2 = strlen(s);
  return memcpy((char *)this + 4, s, v2);
}

//----- (080485F4) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  N *v3; // ebx
  N *v4; // ebx
  N *v6; // [esp+1Ch] [ebp-8h]

  if ( argc <= 1 )
    _exit(1);
  v3 = (N *)operator new(0x6Cu);
  N::N(v3, 5);
  v6 = v3;
  v4 = (N *)operator new(0x6Cu);
  N::N(v4, 6);
  N::setAnnotation(v6, (char *)argv[1]);
  return (**(int (__cdecl ***)(N *, N *))v4)(v4, v6);
}

//----- (0804869A) --------------------------------------------------------
int __cdecl __static_initialization_and_destruction_0(int a1, int a2)
{
  int result; // eax

  if ( a1 == 1 && a2 == 0xFFFF )
  {
    std::ios_base::Init::Init((std::ios_base::Init *)&std::__ioinit);
    return __cxa_atexit(std::ios_base::Init::~Init, &std::__ioinit, &_dso_handle);
  }
  return result;
}

//----- (080486DA) --------------------------------------------------------
int GLOBAL__sub_I_main()
{
  return __static_initialization_and_destruction_0(1, 0xFFFF);
}

//----- (080486F6) --------------------------------------------------------
void __cdecl N::N(N *this, int a2)
{
  *(_DWORD *)this = off_8048848;
  *((_DWORD *)this + 26) = a2;
}
// 8048848: using guessed type int (__cdecl *off_8048848[2])(int, int);



//----- (0804873A) --------------------------------------------------------
int __cdecl N::operator+(int a1, int a2)
{
  return *(_DWORD *)(a1 + 104) + *(_DWORD *)(a2 + 104);
}

//----- (0804874E) --------------------------------------------------------
int __cdecl N::operator-(int a1, int a2)
{
  return *(_DWORD *)(a1 + 104) - *(_DWORD *)(a2 + 104);
}

//----- (08048770) --------------------------------------------------------
void _libc_csu_init(void)
{
  int v0; // edi
  int i; // esi

  init_proc();
  v0 = ((char *)&_CTOR_LIST__ - ((char *)&GLOBAL_OFFSET_TABLE_ + (_DWORD)(&_init_array_start - 33629905))) >> 2;
  if ( v0 )
  {
    for ( i = 0; i != v0; ++i )
      (*(&_init_array_start + i))();
  }
}
// 8049A48: using guessed type int (*_init_array_start)();
// 8049A4C: using guessed type int _CTOR_LIST__;
// 8049B44: using guessed type Elf32_Dyn *GLOBAL_OFFSET_TABLE_;

//----- (080487F0) --------------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
  void (*result)(void); // eax
  void (**v1)(void); // ebx

  result = (void (*)(void))_CTOR_LIST__;
  if ( _CTOR_LIST__ != -1 )
  {
    v1 = (void (**)(void))&_CTOR_LIST__;
    do
    {
      --v1;
      result();
      result = *v1;
    }
    while ( *v1 != (void (*)(void))-1 );
  }
  return result;
}
// 8049A4C: using guessed type int _CTOR_LIST__;

//----- (0804881C) --------------------------------------------------------
void term_proc()
{
  _do_global_dtors_aux();
}

// nfuncs=35 queued=15 decompiled=15 lumina nreq=0 worse=0 better=0
// ALL OK, 15 function(s) have been successfully decompiled
